name: test
on:
  workflow_dispatch:
jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      max-parallel: 1
      matrix:
        os:
          - windows-2025
          - windows-2022
          - windows-2019
          - windows-11-arm
          - ubuntu-24.04-arm
          - ubuntu-24.04
          - ubuntu-22.04-arm
          - ubuntu-22.04
          - macos-15
          - macos-14
          - macos-13
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Configure git for commit
        shell: bash
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "${GITHUB_REPOSITORY//\//+}+${GITHUB_WORKFLOW// /-}@github.io"
          git pull --ff-only
      - name: Run test
        shell: bash
        run: |
          :
          : setup
          :
          python3 -m venv .venv
          for b in bin Scripts
          do
            a=.venv/$b/activate
            if [[ -f "$a" ]]
            then
              source "$a"
              break
            fi
          done
          pip install platformdirs
          mkdir -p results
          :
          : test
          :
          o=results/${{ matrix.os }}.txt
          python -m platformdirs > "$o"
          cat -- "$o"
      - name: Push any changes
        shell: bash
        run: |
          git add results
          if ! git diff --cached --name-status --exit-code
          then
            git commit -m 'something has changed on ${{ matrix.os }}'
            git push
          fi
